/*
 * Elenco di frasi per il gioco "Leggi una frase".
 *
 * Ogni frase e' un elenco di "blocchetti" (uno per parola), nello stesso
 * ordine in cui vanno lette (l'ordine NON viene rimescolato). Ogni
 * blocchetto e' un oggetto con:
 *   - parola: il testo mostrato in grande (la prima parola della frase e'
 *     maiuscola, l'ultima porta il punto finale, come in una frase scritta)
 *   - sillabe: la struttura sillabica mostrata in piccolo sotto la parola
 *     (sempre presente, anche per le congiunzioni).
 *   - tipo: "verbo" per i verbi (mostrati con un colore leggermente
 *     diverso), "congiunzione" per le congiunzioni (solo per riferimento,
 *     non cambia l'aspetto); omesso per le parole "normali" (nomi,
 *     articoli, preposizioni, aggettivi bisillabi o trisillabi).
 *
 * Frasi scelte, composte e sillabate a mano da Claude: ogni frase ha tra
 * 6 e 15 parole, di senso compiuto, usando per lo piu' le stesse
 * bisillabe/trisillabe gia' note al bambino dagli altri due giochi di
 * lettura, piu' semplici verbi elementari e congiunzioni.
 */

const FRASI = [
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "cane", sillabe: "ca-ne" },
    { parola: "corre", sillabe: "cor-re", tipo: "verbo" },
    { parola: "nel", sillabe: "nel" },
    { parola: "prato", sillabe: "pra-to" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "gioca", sillabe: "gio-ca", tipo: "verbo" },
    { parola: "con", sillabe: "con" },
    { parola: "il", sillabe: "il" },
    { parola: "pallone.", sillabe: "pal-lo-ne" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "bambina", sillabe: "bam-bi-na" },
    { parola: "disegna", sillabe: "di-se-gna", tipo: "verbo" },
    { parola: "una", sillabe: "u-na" },
    { parola: "stella", sillabe: "stel-la" },
    { parola: "sul", sillabe: "sul" },
    { parola: "quaderno.", sillabe: "qua-der-no" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "leone", sillabe: "le-o-ne" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "la", sillabe: "la" },
    { parola: "giraffa", sillabe: "gi-raf-fa" },
    { parola: "camminano", sillabe: "cam-mi-na-no", tipo: "verbo" },
    { parola: "nel", sillabe: "nel" },
    { parola: "deserto", sillabe: "de-ser-to" },
    { parola: "caldo.", sillabe: "cal-do" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "topo", sillabe: "to-po" },
    { parola: "mangia", sillabe: "man-gia", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "formaggio", sillabe: "for-mag-gio" },
    { parola: "dentro", sillabe: "den-tro" },
    { parola: "la", sillabe: "la" },
    { parola: "cucina.", sillabe: "cu-ci-na" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "maestra", sillabe: "ma-e-stra" },
    { parola: "legge", sillabe: "leg-ge", tipo: "verbo" },
    { parola: "una", sillabe: "u-na" },
    { parola: "frase", sillabe: "fra-se" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "i", sillabe: "i" },
    { parola: "bambini", sillabe: "bam-bi-ni" },
    { parola: "ascoltano.", sillabe: "a-scol-ta-no", tipo: "verbo" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "delfino", sillabe: "del-fi-no" },
    { parola: "nuota", sillabe: "nuo-ta", tipo: "verbo" },
    { parola: "veloce", sillabe: "ve-lo-ce" },
    { parola: "nel", sillabe: "nel" },
    { parola: "mare", sillabe: "ma-re" },
    { parola: "blu.", sillabe: "blu" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "regina", sillabe: "re-gi-na" },
    { parola: "indossa", sillabe: "in-dos-sa", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "corona", sillabe: "co-ro-na" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "cammina", sillabe: "cam-mi-na", tipo: "verbo" },
    { parola: "nel", sillabe: "nel" },
    { parola: "castello.", sillabe: "ca-stel-lo" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "gabbiano", sillabe: "gab-bia-no" },
    { parola: "vola", sillabe: "vo-la", tipo: "verbo" },
    { parola: "sopra", sillabe: "so-pra" },
    { parola: "il", sillabe: "il" },
    { parola: "mare", sillabe: "ma-re" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "il", sillabe: "il" },
    { parola: "vento", sillabe: "ven-to" },
    { parola: "soffia.", sillabe: "sof-fia", tipo: "verbo" },
  ],
  [
    { parola: "I", sillabe: "I" },
    { parola: "bambini", sillabe: "bam-bi-ni" },
    { parola: "giocano", sillabe: "gio-ca-no", tipo: "verbo" },
    { parola: "nel", sillabe: "nel" },
    { parola: "giardino", sillabe: "giar-di-no" },
    { parola: "mentre", sillabe: "men-tre", tipo: "congiunzione" },
    { parola: "il", sillabe: "il" },
    { parola: "sole", sillabe: "so-le" },
    { parola: "splende.", sillabe: "splen-de", tipo: "verbo" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "civetta", sillabe: "ci-vet-ta" },
    { parola: "guarda", sillabe: "guar-da", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "luna", sillabe: "lu-na" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "ascolta", sillabe: "a-scol-ta", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "vento", sillabe: "ven-to" },
    { parola: "tra", sillabe: "tra" },
    { parola: "gli", sillabe: "gli" },
    { parola: "alberi.", sillabe: "al-be-ri" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "nonno", sillabe: "non-no" },
    { parola: "racconta", sillabe: "rac-con-ta", tipo: "verbo" },
    { parola: "una", sillabe: "u-na" },
    { parola: "storia", sillabe: "sto-ria" },
    { parola: "mentre", sillabe: "men-tre", tipo: "congiunzione" },
    { parola: "i", sillabe: "i" },
    { parola: "nipoti", sillabe: "ni-po-ti" },
    { parola: "ridono", sillabe: "ri-do-no", tipo: "verbo" },
    { parola: "felici.", sillabe: "fe-li-ci" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "gatto", sillabe: "gat-to" },
    { parola: "sale", sillabe: "sa-le", tipo: "verbo" },
    { parola: "sopra", sillabe: "so-pra" },
    { parola: "il", sillabe: "il" },
    { parola: "muro.", sillabe: "mu-ro" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "cavallo", sillabe: "ca-val-lo" },
    { parola: "corre", sillabe: "cor-re", tipo: "verbo" },
    { parola: "veloce", sillabe: "ve-lo-ce" },
    { parola: "nel", sillabe: "nel" },
    { parola: "prato", sillabe: "pra-to" },
    { parola: "mentre", sillabe: "men-tre", tipo: "congiunzione" },
    { parola: "il", sillabe: "il" },
    { parola: "cane", sillabe: "ca-ne" },
    { parola: "abbaia", sillabe: "ab-ba-ia", tipo: "verbo" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "la", sillabe: "la" },
    { parola: "gallina", sillabe: "gal-li-na" },
    { parola: "scappa.", sillabe: "scap-pa", tipo: "verbo" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "farfalla", sillabe: "far-fal-la" },
    { parola: "vola", sillabe: "vo-la", tipo: "verbo" },
    { parola: "sopra", sillabe: "so-pra" },
    { parola: "i", sillabe: "i" },
    { parola: "fiori", sillabe: "fio-ri" },
    { parola: "mentre", sillabe: "men-tre", tipo: "congiunzione" },
    { parola: "il", sillabe: "il" },
    { parola: "sole", sillabe: "so-le" },
    { parola: "splende", sillabe: "splen-de", tipo: "verbo" },
    { parola: "forte.", sillabe: "for-te" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "dottore", sillabe: "dot-to-re" },
    { parola: "visita", sillabe: "vi-si-ta", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "bambino", sillabe: "bam-bi-no" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "sorride.", sillabe: "sor-ri-de", tipo: "verbo" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "pinguino", sillabe: "pin-gui-no" },
    { parola: "nuota", sillabe: "nuo-ta", tipo: "verbo" },
    { parola: "nel", sillabe: "nel" },
    { parola: "mare", sillabe: "ma-re" },
    { parola: "gelido", sillabe: "ge-li-do" },
    { parola: "mentre", sillabe: "men-tre", tipo: "congiunzione" },
    { parola: "la", sillabe: "la" },
    { parola: "balena", sillabe: "ba-le-na" },
    { parola: "canta", sillabe: "can-ta", tipo: "verbo" },
    { parola: "piano.", sillabe: "pia-no" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "coniglio", sillabe: "co-ni-glio" },
    { parola: "salta", sillabe: "sal-ta", tipo: "verbo" },
    { parola: "veloce", sillabe: "ve-lo-ce" },
    { parola: "ma", sillabe: "ma", tipo: "congiunzione" },
    { parola: "la", sillabe: "la" },
    { parola: "lumaca", sillabe: "lu-ma-ca" },
    { parola: "cammina", sillabe: "cam-mi-na", tipo: "verbo" },
    { parola: "piano.", sillabe: "pia-no" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "mamma", sillabe: "mam-ma" },
    { parola: "prepara", sillabe: "pre-pa-ra", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "merenda", sillabe: "me-ren-da" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "i", sillabe: "i" },
    { parola: "bambini", sillabe: "bam-bi-ni" },
    { parola: "mangiano", sillabe: "man-gia-no", tipo: "verbo" },
    { parola: "felici.", sillabe: "fe-li-ci" },
  ],
];
