/*
 * Elenco di frasi per il gioco "Leggi una frase".
 *
 * Ogni frase e' un elenco di "blocchetti" (uno per parola), nello stesso
 * ordine in cui vanno lette (l'ordine NON viene rimescolato). Ogni
 * blocchetto e' un oggetto con:
 *   - parola: il testo mostrato in grande (la prima parola della frase e'
 *     maiuscola, l'ultima porta il punto finale, come in una frase scritta)
 *   - sillabe: la struttura sillabica mostrata in piccolo sotto la parola
 *     (sempre presente, anche per le congiunzioni).
 *   - tipo: "verbo" per i verbi (mostrati con un colore leggermente
 *     diverso), "congiunzione" per le congiunzioni (solo per riferimento,
 *     non cambia l'aspetto); omesso per le parole "normali" (nomi,
 *     articoli, preposizioni, aggettivi bisillabi o trisillabi).
 *
 * Frasi scelte, composte e sillabate a mano da Claude: ogni frase ha tra
 * 6 e 15 parole, di senso compiuto, usando per lo piu' le stesse
 * bisillabe/trisillabe gia' note al bambino dagli altri due giochi di
 * lettura, piu' semplici verbi elementari e congiunzioni.
 */

const FRASI = [
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "cane", sillabe: "ca-ne" },
    { parola: "corre", sillabe: "cor-re", tipo: "verbo" },
    { parola: "nel", sillabe: "nel" },
    { parola: "prato", sillabe: "pra-to" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "gioca", sillabe: "gio-ca", tipo: "verbo" },
    { parola: "con", sillabe: "con" },
    { parola: "il", sillabe: "il" },
    { parola: "pallone.", sillabe: "pal-lo-ne" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "bambina", sillabe: "bam-bi-na" },
    { parola: "disegna", sillabe: "di-se-gna", tipo: "verbo" },
    { parola: "una", sillabe: "u-na" },
    { parola: "stella", sillabe: "stel-la" },
    { parola: "sul", sillabe: "sul" },
    { parola: "quaderno.", sillabe: "qua-der-no" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "leone", sillabe: "le-o-ne" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "la", sillabe: "la" },
    { parola: "giraffa", sillabe: "gi-raf-fa" },
    { parola: "camminano", sillabe: "cam-mi-na-no", tipo: "verbo" },
    { parola: "nel", sillabe: "nel" },
    { parola: "deserto", sillabe: "de-ser-to" },
    { parola: "caldo.", sillabe: "cal-do" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "topo", sillabe: "to-po" },
    { parola: "mangia", sillabe: "man-gia", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "formaggio", sillabe: "for-mag-gio" },
    { parola: "dentro", sillabe: "den-tro" },
    { parola: "la", sillabe: "la" },
    { parola: "cucina.", sillabe: "cu-ci-na" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "maestra", sillabe: "ma-e-stra" },
    { parola: "legge", sillabe: "leg-ge", tipo: "verbo" },
    { parola: "una", sillabe: "u-na" },
    { parola: "frase", sillabe: "fra-se" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "i", sillabe: "i" },
    { parola: "bambini", sillabe: "bam-bi-ni" },
    { parola: "ascoltano.", sillabe: "a-scol-ta-no", tipo: "verbo" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "delfino", sillabe: "del-fi-no" },
    { parola: "nuota", sillabe: "nuo-ta", tipo: "verbo" },
    { parola: "veloce", sillabe: "ve-lo-ce" },
    { parola: "nel", sillabe: "nel" },
    { parola: "mare", sillabe: "ma-re" },
    { parola: "blu.", sillabe: "blu" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "regina", sillabe: "re-gi-na" },
    { parola: "indossa", sillabe: "in-dos-sa", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "corona", sillabe: "co-ro-na" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "cammina", sillabe: "cam-mi-na", tipo: "verbo" },
    { parola: "nel", sillabe: "nel" },
    { parola: "castello.", sillabe: "ca-stel-lo" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "gabbiano", sillabe: "gab-bia-no" },
    { parola: "vola", sillabe: "vo-la", tipo: "verbo" },
    { parola: "sopra", sillabe: "so-pra" },
    { parola: "il", sillabe: "il" },
    { parola: "mare", sillabe: "ma-re" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "il", sillabe: "il" },
    { parola: "vento", sillabe: "ven-to" },
    { parola: "soffia.", sillabe: "sof-fia", tipo: "verbo" },
  ],
  [
    { parola: "I", sillabe: "I" },
    { parola: "bambini", sillabe: "bam-bi-ni" },
    { parola: "giocano", sillabe: "gio-ca-no", tipo: "verbo" },
    { parola: "nel", sillabe: "nel" },
    { parola: "giardino", sillabe: "giar-di-no" },
    { parola: "mentre", sillabe: "men-tre", tipo: "congiunzione" },
    { parola: "il", sillabe: "il" },
    { parola: "sole", sillabe: "so-le" },
    { parola: "splende.", sillabe: "splen-de", tipo: "verbo" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "civetta", sillabe: "ci-vet-ta" },
    { parola: "guarda", sillabe: "guar-da", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "luna", sillabe: "lu-na" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "ascolta", sillabe: "a-scol-ta", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "vento", sillabe: "ven-to" },
    { parola: "tra", sillabe: "tra" },
    { parola: "gli", sillabe: "gli" },
    { parola: "alberi.", sillabe: "al-be-ri" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "nonno", sillabe: "non-no" },
    { parola: "racconta", sillabe: "rac-con-ta", tipo: "verbo" },
    { parola: "una", sillabe: "u-na" },
    { parola: "storia", sillabe: "sto-ria" },
    { parola: "mentre", sillabe: "men-tre", tipo: "congiunzione" },
    { parola: "i", sillabe: "i" },
    { parola: "nipoti", sillabe: "ni-po-ti" },
    { parola: "ridono", sillabe: "ri-do-no", tipo: "verbo" },
    { parola: "felici.", sillabe: "fe-li-ci" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "gatto", sillabe: "gat-to" },
    { parola: "sale", sillabe: "sa-le", tipo: "verbo" },
    { parola: "sopra", sillabe: "so-pra" },
    { parola: "il", sillabe: "il" },
    { parola: "muro.", sillabe: "mu-ro" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "cavallo", sillabe: "ca-val-lo" },
    { parola: "corre", sillabe: "cor-re", tipo: "verbo" },
    { parola: "veloce", sillabe: "ve-lo-ce" },
    { parola: "nel", sillabe: "nel" },
    { parola: "prato", sillabe: "pra-to" },
    { parola: "mentre", sillabe: "men-tre", tipo: "congiunzione" },
    { parola: "il", sillabe: "il" },
    { parola: "cane", sillabe: "ca-ne" },
    { parola: "abbaia", sillabe: "ab-ba-ia", tipo: "verbo" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "la", sillabe: "la" },
    { parola: "gallina", sillabe: "gal-li-na" },
    { parola: "scappa.", sillabe: "scap-pa", tipo: "verbo" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "farfalla", sillabe: "far-fal-la" },
    { parola: "vola", sillabe: "vo-la", tipo: "verbo" },
    { parola: "sopra", sillabe: "so-pra" },
    { parola: "i", sillabe: "i" },
    { parola: "fiori", sillabe: "fio-ri" },
    { parola: "mentre", sillabe: "men-tre", tipo: "congiunzione" },
    { parola: "il", sillabe: "il" },
    { parola: "sole", sillabe: "so-le" },
    { parola: "splende", sillabe: "splen-de", tipo: "verbo" },
    { parola: "forte.", sillabe: "for-te" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "dottore", sillabe: "dot-to-re" },
    { parola: "visita", sillabe: "vi-si-ta", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "bambino", sillabe: "bam-bi-no" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "sorride.", sillabe: "sor-ri-de", tipo: "verbo" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "pinguino", sillabe: "pin-gui-no" },
    { parola: "nuota", sillabe: "nuo-ta", tipo: "verbo" },
    { parola: "nel", sillabe: "nel" },
    { parola: "mare", sillabe: "ma-re" },
    { parola: "gelido", sillabe: "ge-li-do" },
    { parola: "mentre", sillabe: "men-tre", tipo: "congiunzione" },
    { parola: "la", sillabe: "la" },
    { parola: "balena", sillabe: "ba-le-na" },
    { parola: "canta", sillabe: "can-ta", tipo: "verbo" },
    { parola: "piano.", sillabe: "pia-no" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "coniglio", sillabe: "co-ni-glio" },
    { parola: "salta", sillabe: "sal-ta", tipo: "verbo" },
    { parola: "veloce", sillabe: "ve-lo-ce" },
    { parola: "ma", sillabe: "ma", tipo: "congiunzione" },
    { parola: "la", sillabe: "la" },
    { parola: "lumaca", sillabe: "lu-ma-ca" },
    { parola: "cammina", sillabe: "cam-mi-na", tipo: "verbo" },
    { parola: "piano.", sillabe: "pia-no" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "mamma", sillabe: "mam-ma" },
    { parola: "prepara", sillabe: "pre-pa-ra", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "merenda", sillabe: "me-ren-da" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "i", sillabe: "i" },
    { parola: "bambini", sillabe: "bam-bi-ni" },
    { parola: "mangiano", sillabe: "man-gia-no", tipo: "verbo" },
    { parola: "felici.", sillabe: "fe-li-ci" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "mucca", sillabe: "muc-ca" },
    { parola: "mangia", sillabe: "man-gia", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "fieno", sillabe: "fie-no" },
    { parola: "nella", sillabe: "nel-la" },
    { parola: "stalla.", sillabe: "stal-la" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "maiale", sillabe: "ma-ia-le" },
    { parola: "dorme", sillabe: "dor-me", tipo: "verbo" },
    { parola: "nel", sillabe: "nel" },
    { parola: "fango", sillabe: "fan-go" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "la", sillabe: "la" },
    { parola: "gallina", sillabe: "gal-li-na" },
    { parola: "becca", sillabe: "bec-ca", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "grano.", sillabe: "gra-no" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "cavallo", sillabe: "ca-val-lo" },
    { parola: "beve", sillabe: "be-ve", tipo: "verbo" },
    { parola: "acqua", sillabe: "ac-qua" },
    { parola: "fresca", sillabe: "fre-sca" },
    { parola: "dal", sillabe: "dal" },
    { parola: "ruscello.", sillabe: "ru-scel-lo" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "pecora", sillabe: "pe-co-ra" },
    { parola: "salta", sillabe: "sal-ta", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "muretto", sillabe: "mu-ret-to" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "segue", sillabe: "se-gue", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "pastore.", sillabe: "pa-sto-re" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "pulcino", sillabe: "pul-ci-no" },
    { parola: "cerca", sillabe: "cer-ca", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "mamma", sillabe: "mam-ma" },
    { parola: "ma", sillabe: "ma", tipo: "congiunzione" },
    { parola: "la", sillabe: "la" },
    { parola: "gallina", sillabe: "gal-li-na" },
    { parola: "dorme.", sillabe: "dor-me", tipo: "verbo" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "contadino", sillabe: "con-ta-di-no" },
    { parola: "guida", sillabe: "gui-da", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "trattore", sillabe: "trat-to-re" },
    { parola: "nel", sillabe: "nel" },
    { parola: "campo", sillabe: "cam-po" },
    { parola: "grande.", sillabe: "gran-de" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "rana", sillabe: "ra-na" },
    { parola: "salta", sillabe: "sal-ta", tipo: "verbo" },
    { parola: "nello", sillabe: "nel-lo" },
    { parola: "stagno", sillabe: "sta-gno" },
    { parola: "mentre", sillabe: "men-tre", tipo: "congiunzione" },
    { parola: "il", sillabe: "il" },
    { parola: "pesce", sillabe: "pe-sce" },
    { parola: "nuota", sillabe: "nuo-ta", tipo: "verbo" },
    { parola: "piano.", sillabe: "pia-no" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "lupo", sillabe: "lu-po" },
    { parola: "corre", sillabe: "cor-re", tipo: "verbo" },
    { parola: "nel", sillabe: "nel" },
    { parola: "bosco", sillabe: "bo-sco" },
    { parola: "perché", sillabe: "per-ché", tipo: "congiunzione" },
    { parola: "cerca", sillabe: "cer-ca", tipo: "verbo" },
    { parola: "del", sillabe: "del" },
    { parola: "cibo.", sillabe: "ci-bo" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "volpe", sillabe: "vol-pe" },
    { parola: "scappa", sillabe: "scap-pa", tipo: "verbo" },
    { parola: "veloce", sillabe: "ve-lo-ce" },
    { parola: "quando", sillabe: "quan-do", tipo: "congiunzione" },
    { parola: "il", sillabe: "il" },
    { parola: "cane", sillabe: "ca-ne" },
    { parola: "abbaia", sillabe: "ab-ba-ia", tipo: "verbo" },
    { parola: "forte.", sillabe: "for-te" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "topolino", sillabe: "to-po-li-no" },
    { parola: "entra", sillabe: "en-tra", tipo: "verbo" },
    { parola: "nella", sillabe: "nel-la" },
    { parola: "casa", sillabe: "ca-sa" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "trova", sillabe: "tro-va", tipo: "verbo" },
    { parola: "un", sillabe: "un" },
    { parola: "pezzo", sillabe: "pez-zo" },
    { parola: "di", sillabe: "di" },
    { parola: "pane.", sillabe: "pa-ne" },
  ],
  [
    { parola: "Le", sillabe: "Le" },
    { parola: "api", sillabe: "a-pi" },
    { parola: "volano", sillabe: "vo-la-no", tipo: "verbo" },
    { parola: "sui", sillabe: "sui" },
    { parola: "fiori", sillabe: "fio-ri" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "portano", sillabe: "por-ta-no", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "miele.", sillabe: "mie-le" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "ragno", sillabe: "ra-gno" },
    { parola: "tesse", sillabe: "tes-se", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "tela", sillabe: "te-la" },
    { parola: "sul", sillabe: "sul" },
    { parola: "muro.", sillabe: "mu-ro" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "coniglio", sillabe: "co-ni-glio" },
    { parola: "mangia", sillabe: "man-gia", tipo: "verbo" },
    { parola: "una", sillabe: "u-na" },
    { parola: "carota", sillabe: "ca-ro-ta" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "salta", sillabe: "sal-ta", tipo: "verbo" },
    { parola: "nel", sillabe: "nel" },
    { parola: "prato.", sillabe: "pra-to" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "tartaruga", sillabe: "tar-ta-ru-ga" },
    { parola: "cammina", sillabe: "cam-mi-na", tipo: "verbo" },
    { parola: "piano", sillabe: "pia-no" },
    { parola: "ma", sillabe: "ma", tipo: "congiunzione" },
    { parola: "arriva", sillabe: "ar-ri-va", tipo: "verbo" },
    { parola: "sempre.", sillabe: "sem-pre" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "leone", sillabe: "le-o-ne" },
    { parola: "ruggisce", sillabe: "rug-gi-sce", tipo: "verbo" },
    { parola: "forte", sillabe: "for-te" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "gli", sillabe: "gli" },
    { parola: "animali", sillabe: "a-ni-ma-li" },
    { parola: "scappano", sillabe: "scap-pa-no", tipo: "verbo" },
    { parola: "via.", sillabe: "vi-a" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "scimmia", sillabe: "scim-mia" },
    { parola: "mangia", sillabe: "man-gia", tipo: "verbo" },
    { parola: "una", sillabe: "u-na" },
    { parola: "banana", sillabe: "ba-na-na" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "salta", sillabe: "sal-ta", tipo: "verbo" },
    { parola: "sul", sillabe: "sul" },
    { parola: "ramo.", sillabe: "ra-mo" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "grosso", sillabe: "gros-so" },
    { parola: "elefante", sillabe: "e-le-fan-te" },
    { parola: "cammina", sillabe: "cam-mi-na", tipo: "verbo" },
    { parola: "nella", sillabe: "nel-la" },
    { parola: "savana.", sillabe: "sa-va-na" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "giraffa", sillabe: "gi-raf-fa" },
    { parola: "mangia", sillabe: "man-gia", tipo: "verbo" },
    { parola: "le", sillabe: "le" },
    { parola: "foglie", sillabe: "fo-glie" },
    { parola: "alte.", sillabe: "al-te" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "cane", sillabe: "ca-ne" },
    { parola: "porta", sillabe: "por-ta", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "bastone", sillabe: "ba-sto-ne" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "scodinzola", sillabe: "sco-din-zo-la", tipo: "verbo" },
    { parola: "felice.", sillabe: "fe-li-ce" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "gatto", sillabe: "gat-to" },
    { parola: "miagola", sillabe: "mia-go-la", tipo: "verbo" },
    { parola: "perché", sillabe: "per-ché", tipo: "congiunzione" },
    { parola: "vuole", sillabe: "vuo-le", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "latte.", sillabe: "lat-te" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "papà", sillabe: "pa-pà" },
    { parola: "legge", sillabe: "leg-ge", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "giornale", sillabe: "gior-na-le" },
    { parola: "mentre", sillabe: "men-tre", tipo: "congiunzione" },
    { parola: "la", sillabe: "la" },
    { parola: "mamma", sillabe: "mam-ma" },
    { parola: "cucina.", sillabe: "cu-ci-na", tipo: "verbo" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "sorella", sillabe: "so-rel-la" },
    { parola: "pettina", sillabe: "pet-ti-na", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "bambola", sillabe: "bam-bo-la" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "canta", sillabe: "can-ta", tipo: "verbo" },
    { parola: "una", sillabe: "u-na" },
    { parola: "canzone.", sillabe: "can-zo-ne" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "fratello", sillabe: "fra-tel-lo" },
    { parola: "costruisce", sillabe: "co-strui-sce", tipo: "verbo" },
    { parola: "una", sillabe: "u-na" },
    { parola: "torre", sillabe: "tor-re" },
    { parola: "con", sillabe: "con" },
    { parola: "i", sillabe: "i" },
    { parola: "mattoncini.", sillabe: "mat-ton-ci-ni" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "nonna", sillabe: "non-na" },
    { parola: "lava", sillabe: "la-va", tipo: "verbo" },
    { parola: "i", sillabe: "i" },
    { parola: "piatti", sillabe: "piat-ti" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "il", sillabe: "il" },
    { parola: "nonno", sillabe: "non-no" },
    { parola: "asciuga", sillabe: "a-sciu-ga", tipo: "verbo" },
    { parola: "i", sillabe: "i" },
    { parola: "bicchieri.", sillabe: "bic-chie-ri" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "mamma", sillabe: "mam-ma" },
    { parola: "apre", sillabe: "a-pre", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "finestra", sillabe: "fi-ne-stra" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "entra", sillabe: "en-tra", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "sole.", sillabe: "so-le" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "papà", sillabe: "pa-pà" },
    { parola: "accende", sillabe: "ac-cen-de", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "luce", sillabe: "lu-ce" },
    { parola: "quando", sillabe: "quan-do", tipo: "congiunzione" },
    { parola: "arriva", sillabe: "ar-ri-va", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "sera.", sillabe: "se-ra" },
  ],
  [
    { parola: "I", sillabe: "I" },
    { parola: "nonni", sillabe: "non-ni" },
    { parola: "guardano", sillabe: "guar-da-no", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "televisione", sillabe: "te-le-vi-sio-ne" },
    { parola: "sul", sillabe: "sul" },
    { parola: "divano.", sillabe: "di-va-no" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "zia", sillabe: "zi-a" },
    { parola: "porta", sillabe: "por-ta", tipo: "verbo" },
    { parola: "un", sillabe: "un" },
    { parola: "regalo", sillabe: "re-ga-lo" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "i", sillabe: "i" },
    { parola: "bimbi", sillabe: "bim-bi" },
    { parola: "saltano", sillabe: "sal-ta-no", tipo: "verbo" },
    { parola: "di", sillabe: "di" },
    { parola: "gioia.", sillabe: "gio-ia" },
  ],
  [
    { parola: "Lo", sillabe: "Lo" },
    { parola: "zio", sillabe: "zi-o" },
    { parola: "ripara", sillabe: "ri-pa-ra", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "bicicletta", sillabe: "bi-ci-clet-ta" },
    { parola: "nel", sillabe: "nel" },
    { parola: "garage.", sillabe: "ga-ra-ge" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "bambina", sillabe: "bam-bi-na" },
    { parola: "apparecchia", sillabe: "ap-pa-rec-chia", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "tavola", sillabe: "ta-vo-la" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "mette", sillabe: "met-te", tipo: "verbo" },
    { parola: "i", sillabe: "i" },
    { parola: "bicchieri.", sillabe: "bic-chie-ri" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "bimbo", sillabe: "bim-bo" },
    { parola: "dorme", sillabe: "dor-me", tipo: "verbo" },
    { parola: "nel", sillabe: "nel" },
    { parola: "lettino", sillabe: "let-ti-no" },
    { parola: "mentre", sillabe: "men-tre", tipo: "congiunzione" },
    { parola: "la", sillabe: "la" },
    { parola: "mamma", sillabe: "mam-ma" },
    { parola: "canta", sillabe: "can-ta", tipo: "verbo" },
    { parola: "piano.", sillabe: "pia-no" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "sorella", sillabe: "so-rel-la" },
    { parola: "abbraccia", sillabe: "ab-brac-cia", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "fratellino", sillabe: "fra-tel-li-no" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "ride", sillabe: "ri-de", tipo: "verbo" },
    { parola: "felice.", sillabe: "fe-li-ce" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "cugino", sillabe: "cu-gi-no" },
    { parola: "viene", sillabe: "vie-ne", tipo: "verbo" },
    { parola: "a", sillabe: "a" },
    { parola: "casa", sillabe: "ca-sa" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "porta", sillabe: "por-ta", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "pallone.", sillabe: "pal-lo-ne" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "mamma", sillabe: "mam-ma" },
    { parola: "stende", sillabe: "sten-de", tipo: "verbo" },
    { parola: "i", sillabe: "i" },
    { parola: "panni", sillabe: "pan-ni" },
    { parola: "al", sillabe: "al" },
    { parola: "sole.", sillabe: "so-le" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "papà", sillabe: "pa-pà" },
    { parola: "taglia", sillabe: "ta-glia", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "pane", sillabe: "pa-ne" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "la", sillabe: "la" },
    { parola: "mamma", sillabe: "mam-ma" },
    { parola: "versa", sillabe: "ver-sa", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "latte.", sillabe: "lat-te" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "famiglia", sillabe: "fa-mi-glia" },
    { parola: "mangia", sillabe: "man-gia", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "pizza", sillabe: "piz-za" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "beve", sillabe: "be-ve", tipo: "verbo" },
    { parola: "acqua", sillabe: "ac-qua" },
    { parola: "fresca.", sillabe: "fre-sca" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "mamma", sillabe: "mam-ma" },
    { parola: "chiude", sillabe: "chiu-de", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "porta", sillabe: "por-ta" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "spegne", sillabe: "spe-gne", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "luce.", sillabe: "lu-ce" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "nonno", sillabe: "non-no" },
    { parola: "racconta", sillabe: "rac-con-ta", tipo: "verbo" },
    { parola: "una", sillabe: "u-na" },
    { parola: "favola", sillabe: "fa-vo-la" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "i", sillabe: "i" },
    { parola: "nipoti", sillabe: "ni-po-ti" },
    { parola: "ascoltano", sillabe: "a-scol-ta-no", tipo: "verbo" },
    { parola: "zitti.", sillabe: "zit-ti" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "bambino", sillabe: "bam-bi-no" },
    { parola: "fa", sillabe: "fa", tipo: "verbo" },
    { parola: "i", sillabe: "i" },
    { parola: "compiti", sillabe: "com-pi-ti" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "la", sillabe: "la" },
    { parola: "mamma", sillabe: "mam-ma" },
    { parola: "controlla.", sillabe: "con-trol-la", tipo: "verbo" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "maestra", sillabe: "ma-e-stra" },
    { parola: "scrive", sillabe: "scri-ve", tipo: "verbo" },
    { parola: "sulla", sillabe: "sul-la" },
    { parola: "lavagna", sillabe: "la-va-gna" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "i", sillabe: "i" },
    { parola: "bambini", sillabe: "bam-bi-ni" },
    { parola: "copiano.", sillabe: "co-pia-no", tipo: "verbo" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "bambino", sillabe: "bam-bi-no" },
    { parola: "apre", sillabe: "a-pre", tipo: "verbo" },
    { parola: "lo", sillabe: "lo" },
    { parola: "zaino", sillabe: "zai-no" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "prende", sillabe: "pren-de", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "quaderno.", sillabe: "qua-der-no" },
  ],
  [
    { parola: "I", sillabe: "I" },
    { parola: "compagni", sillabe: "com-pa-gni" },
    { parola: "leggono", sillabe: "leg-go-no", tipo: "verbo" },
    { parola: "un", sillabe: "un" },
    { parola: "libro", sillabe: "li-bro" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "la", sillabe: "la" },
    { parola: "maestra", sillabe: "ma-e-stra" },
    { parola: "ascolta.", sillabe: "a-scol-ta", tipo: "verbo" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "bambina", sillabe: "bam-bi-na" },
    { parola: "colora", sillabe: "co-lo-ra", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "disegno", sillabe: "di-se-gno" },
    { parola: "con", sillabe: "con" },
    { parola: "le", sillabe: "le" },
    { parola: "matite.", sillabe: "ma-ti-te" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "campanella", sillabe: "cam-pa-nel-la" },
    { parola: "suona", sillabe: "suo-na", tipo: "verbo" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "i", sillabe: "i" },
    { parola: "bambini", sillabe: "bam-bi-ni" },
    { parola: "escono", sillabe: "e-sco-no", tipo: "verbo" },
    { parola: "dalla", sillabe: "dal-la" },
    { parola: "scuola.", sillabe: "scuo-la" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "maestro", sillabe: "ma-e-stro" },
    { parola: "spiega", sillabe: "spie-ga", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "lezione", sillabe: "le-zio-ne" },
    { parola: "mentre", sillabe: "men-tre", tipo: "congiunzione" },
    { parola: "gli", sillabe: "gli" },
    { parola: "alunni", sillabe: "a-lun-ni" },
    { parola: "ascoltano.", sillabe: "a-scol-ta-no", tipo: "verbo" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "bambina", sillabe: "bam-bi-na" },
    { parola: "scrive", sillabe: "scri-ve", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "nome", sillabe: "no-me" },
    { parola: "sul", sillabe: "sul" },
    { parola: "quaderno.", sillabe: "qua-der-no" },
  ],
  [
    { parola: "I", sillabe: "I" },
    { parola: "bambini", sillabe: "bam-bi-ni" },
    { parola: "cantano", sillabe: "can-ta-no", tipo: "verbo" },
    { parola: "una", sillabe: "u-na" },
    { parola: "canzone", sillabe: "can-zo-ne" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "la", sillabe: "la" },
    { parola: "maestra", sillabe: "ma-e-stra" },
    { parola: "suona", sillabe: "suo-na", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "chitarra.", sillabe: "chi-tar-ra" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "bambino", sillabe: "bam-bi-no" },
    { parola: "taglia", sillabe: "ta-glia", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "carta", sillabe: "car-ta" },
    { parola: "con", sillabe: "con" },
    { parola: "le", sillabe: "le" },
    { parola: "forbici.", sillabe: "for-bi-ci" },
  ],
  [
    { parola: "Nella", sillabe: "Nel-la" },
    { parola: "palestra", sillabe: "pa-le-stra" },
    { parola: "i", sillabe: "i" },
    { parola: "bambini", sillabe: "bam-bi-ni" },
    { parola: "saltano", sillabe: "sal-ta-no", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "corda.", sillabe: "cor-da" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "maestra", sillabe: "ma-e-stra" },
    { parola: "porta", sillabe: "por-ta", tipo: "verbo" },
    { parola: "i", sillabe: "i" },
    { parola: "bambini", sillabe: "bam-bi-ni" },
    { parola: "in", sillabe: "in" },
    { parola: "giardino", sillabe: "giar-di-no" },
    { parola: "perché", sillabe: "per-ché", tipo: "congiunzione" },
    { parola: "splende", sillabe: "splen-de", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "sole.", sillabe: "so-le" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "bambino", sillabe: "bam-bi-no" },
    { parola: "impara", sillabe: "im-pa-ra", tipo: "verbo" },
    { parola: "a", sillabe: "a" },
    { parola: "leggere", sillabe: "leg-ge-re" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "la", sillabe: "la" },
    { parola: "mamma", sillabe: "mam-ma" },
    { parola: "sorride.", sillabe: "sor-ri-de", tipo: "verbo" },
  ],
  [
    { parola: "I", sillabe: "I" },
    { parola: "compagni", sillabe: "com-pa-gni" },
    { parola: "giocano", sillabe: "gio-ca-no", tipo: "verbo" },
    { parola: "a", sillabe: "a" },
    { parola: "palla", sillabe: "pal-la" },
    { parola: "nel", sillabe: "nel" },
    { parola: "cortile", sillabe: "cor-ti-le" },
    { parola: "della", sillabe: "del-la" },
    { parola: "scuola.", sillabe: "scuo-la" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "bambina", sillabe: "bam-bi-na" },
    { parola: "prende", sillabe: "pren-de", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "matita", sillabe: "ma-ti-ta" },
    { parola: "ma", sillabe: "ma", tipo: "congiunzione" },
    { parola: "perde", sillabe: "per-de", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "gomma.", sillabe: "gom-ma" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "maestro", sillabe: "ma-e-stro" },
    { parola: "disegna", sillabe: "di-se-gna", tipo: "verbo" },
    { parola: "una", sillabe: "u-na" },
    { parola: "casa", sillabe: "ca-sa" },
    { parola: "sulla", sillabe: "sul-la" },
    { parola: "lavagna.", sillabe: "la-va-gna" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "mamma", sillabe: "mam-ma" },
    { parola: "taglia", sillabe: "ta-glia", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "mela", sillabe: "me-la" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "porta", sillabe: "por-ta", tipo: "verbo" },
    { parola: "una", sillabe: "u-na" },
    { parola: "fetta", sillabe: "fet-ta" },
    { parola: "al", sillabe: "al" },
    { parola: "bambino.", sillabe: "bam-bi-no" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "bambino", sillabe: "bam-bi-no" },
    { parola: "mangia", sillabe: "man-gia", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "gelato", sillabe: "ge-la-to" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "sporca", sillabe: "spor-ca", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "maglietta.", sillabe: "ma-gliet-ta" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "nonna", sillabe: "non-na" },
    { parola: "cuoce", sillabe: "cuo-ce", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "pasta", sillabe: "pa-sta" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "aggiunge", sillabe: "ag-giun-ge", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "sugo.", sillabe: "su-go" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "papà", sillabe: "pa-pà" },
    { parola: "compra", sillabe: "com-pra", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "pane", sillabe: "pa-ne" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "il", sillabe: "il" },
    { parola: "latte", sillabe: "lat-te" },
    { parola: "al", sillabe: "al" },
    { parola: "mercato.", sillabe: "mer-ca-to" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "cuoca", sillabe: "cuo-ca" },
    { parola: "prepara", sillabe: "pre-pa-ra", tipo: "verbo" },
    { parola: "una", sillabe: "u-na" },
    { parola: "torta", sillabe: "tor-ta" },
    { parola: "di", sillabe: "di" },
    { parola: "mele", sillabe: "me-le" },
    { parola: "per", sillabe: "per" },
    { parola: "la", sillabe: "la" },
    { parola: "festa.", sillabe: "fe-sta" },
  ],
  [
    { parola: "I", sillabe: "I" },
    { parola: "bambini", sillabe: "bam-bi-ni" },
    { parola: "bevono", sillabe: "be-vo-no", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "succo", sillabe: "suc-co" },
    { parola: "mentre", sillabe: "men-tre", tipo: "congiunzione" },
    { parola: "mangiano", sillabe: "man-gia-no", tipo: "verbo" },
    { parola: "i", sillabe: "i" },
    { parola: "biscotti.", sillabe: "bi-scot-ti" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "cuoco", sillabe: "cuo-co" },
    { parola: "taglia", sillabe: "ta-glia", tipo: "verbo" },
    { parola: "le", sillabe: "le" },
    { parola: "patate", sillabe: "pa-ta-te" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "accende", sillabe: "ac-cen-de", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "forno.", sillabe: "for-no" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "mamma", sillabe: "mam-ma" },
    { parola: "versa", sillabe: "ver-sa", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "latte", sillabe: "lat-te" },
    { parola: "nella", sillabe: "nel-la" },
    { parola: "tazza", sillabe: "taz-za" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "mescola", sillabe: "me-sco-la", tipo: "verbo" },
    { parola: "piano.", sillabe: "pia-no" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "bimbo", sillabe: "bim-bo" },
    { parola: "sbuccia", sillabe: "sbuc-cia", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "banana", sillabe: "ba-na-na" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "la", sillabe: "la" },
    { parola: "mangia", sillabe: "man-gia", tipo: "verbo" },
    { parola: "piano.", sillabe: "pia-no" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "pizza", sillabe: "piz-za" },
    { parola: "cuoce", sillabe: "cuo-ce", tipo: "verbo" },
    { parola: "nel", sillabe: "nel" },
    { parola: "forno", sillabe: "for-no" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "il", sillabe: "il" },
    { parola: "profumo", sillabe: "pro-fu-mo" },
    { parola: "arriva", sillabe: "ar-ri-va", tipo: "verbo" },
    { parola: "ovunque.", sillabe: "o-vun-que" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "nonno", sillabe: "non-no" },
    { parola: "annaffia", sillabe: "an-naf-fia", tipo: "verbo" },
    { parola: "le", sillabe: "le" },
    { parola: "piante", sillabe: "pian-te" },
    { parola: "nel", sillabe: "nel" },
    { parola: "giardino.", sillabe: "giar-di-no" },
  ],
  [
    { parola: "Le", sillabe: "Le" },
    { parola: "arance", sillabe: "a-ran-ce" },
    { parola: "maturano", sillabe: "ma-tu-ra-no", tipo: "verbo" },
    { parola: "al", sillabe: "al" },
    { parola: "sole", sillabe: "so-le" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "diventano", sillabe: "di-ven-ta-no", tipo: "verbo" },
    { parola: "dolci.", sillabe: "dol-ci" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "sole", sillabe: "so-le" },
    { parola: "scalda", sillabe: "scal-da", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "prato", sillabe: "pra-to" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "i", sillabe: "i" },
    { parola: "fiori", sillabe: "fio-ri" },
    { parola: "si", sillabe: "si" },
    { parola: "aprono.", sillabe: "a-pro-no", tipo: "verbo" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "pioggia", sillabe: "piog-gia" },
    { parola: "cade", sillabe: "ca-de", tipo: "verbo" },
    { parola: "forte", sillabe: "for-te" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "le", sillabe: "le" },
    { parola: "strade", sillabe: "stra-de" },
    { parola: "diventano", sillabe: "di-ven-ta-no", tipo: "verbo" },
    { parola: "bagnate.", sillabe: "ba-gna-te" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "vento", sillabe: "ven-to" },
    { parola: "soffia", sillabe: "sof-fia", tipo: "verbo" },
    { parola: "forte", sillabe: "for-te" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "le", sillabe: "le" },
    { parola: "foglie", sillabe: "fo-glie" },
    { parola: "volano", sillabe: "vo-la-no", tipo: "verbo" },
    { parola: "via.", sillabe: "vi-a" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "neve", sillabe: "ne-ve" },
    { parola: "cade", sillabe: "ca-de", tipo: "verbo" },
    { parola: "piano", sillabe: "pia-no" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "i", sillabe: "i" },
    { parola: "bambini", sillabe: "bam-bi-ni" },
    { parola: "fanno", sillabe: "fan-no", tipo: "verbo" },
    { parola: "un", sillabe: "un" },
    { parola: "pupazzo.", sillabe: "pu-paz-zo" },
  ],
  [
    { parola: "Dopo", sillabe: "Do-po" },
    { parola: "la", sillabe: "la" },
    { parola: "pioggia", sillabe: "piog-gia" },
    { parola: "appare", sillabe: "ap-pa-re", tipo: "verbo" },
    { parola: "un", sillabe: "un" },
    { parola: "arcobaleno", sillabe: "ar-co-ba-le-no" },
    { parola: "nel", sillabe: "nel" },
    { parola: "cielo.", sillabe: "cie-lo" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "luna", sillabe: "lu-na" },
    { parola: "brilla", sillabe: "bril-la", tipo: "verbo" },
    { parola: "nel", sillabe: "nel" },
    { parola: "cielo", sillabe: "cie-lo" },
    { parola: "mentre", sillabe: "men-tre", tipo: "congiunzione" },
    { parola: "le", sillabe: "le" },
    { parola: "stelle", sillabe: "stel-le" },
    { parola: "luccicano.", sillabe: "luc-ci-ca-no", tipo: "verbo" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "fiume", sillabe: "fiu-me" },
    { parola: "scende", sillabe: "scen-de", tipo: "verbo" },
    { parola: "dalla", sillabe: "dal-la" },
    { parola: "montagna", sillabe: "mon-ta-gna" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "arriva", sillabe: "ar-ri-va", tipo: "verbo" },
    { parola: "al", sillabe: "al" },
    { parola: "mare.", sillabe: "ma-re" },
  ],
  [
    { parola: "Le", sillabe: "Le" },
    { parola: "nuvole", sillabe: "nu-vo-le" },
    { parola: "corrono", sillabe: "cor-ro-no", tipo: "verbo" },
    { parola: "nel", sillabe: "nel" },
    { parola: "cielo", sillabe: "cie-lo" },
    { parola: "perché", sillabe: "per-ché", tipo: "congiunzione" },
    { parola: "soffia", sillabe: "sof-fia", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "vento.", sillabe: "ven-to" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "temporale", sillabe: "tem-po-ra-le" },
    { parola: "arriva", sillabe: "ar-ri-va", tipo: "verbo" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "i", sillabe: "i" },
    { parola: "bambini", sillabe: "bam-bi-ni" },
    { parola: "tornano", sillabe: "tor-na-no", tipo: "verbo" },
    { parola: "a", sillabe: "a" },
    { parola: "casa.", sillabe: "ca-sa" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "fuoco", sillabe: "fuo-co" },
    { parola: "scalda", sillabe: "scal-da", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "stanza", sillabe: "stan-za" },
    { parola: "quando", sillabe: "quan-do", tipo: "congiunzione" },
    { parola: "fa", sillabe: "fa", tipo: "verbo" },
    { parola: "freddo.", sillabe: "fred-do" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "mattina", sillabe: "mat-ti-na" },
    { parola: "il", sillabe: "il" },
    { parola: "sole", sillabe: "so-le" },
    { parola: "sorge", sillabe: "sor-ge", tipo: "verbo" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "gli", sillabe: "gli" },
    { parola: "uccelli", sillabe: "uc-cel-li" },
    { parola: "cantano.", sillabe: "can-ta-no", tipo: "verbo" },
  ],
  [
    { parola: "Le", sillabe: "Le" },
    { parola: "onde", sillabe: "on-de" },
    { parola: "bagnano", sillabe: "ba-gna-no", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "sabbia", sillabe: "sab-bia" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "portano", sillabe: "por-ta-no", tipo: "verbo" },
    { parola: "le", sillabe: "le" },
    { parola: "conchiglie.", sillabe: "con-chi-glie" },
  ],
  [
    { parola: "I", sillabe: "I" },
    { parola: "fiori", sillabe: "fio-ri" },
    { parola: "crescono", sillabe: "cre-sco-no", tipo: "verbo" },
    { parola: "nel", sillabe: "nel" },
    { parola: "giardino", sillabe: "giar-di-no" },
    { parola: "quando", sillabe: "quan-do", tipo: "congiunzione" },
    { parola: "piove.", sillabe: "pio-ve", tipo: "verbo" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "nebbia", sillabe: "neb-bia" },
    { parola: "copre", sillabe: "co-pre", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "valle", sillabe: "val-le" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "nessuno", sillabe: "nes-su-no" },
    { parola: "vede", sillabe: "ve-de", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "strada.", sillabe: "stra-da" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "treno", sillabe: "tre-no" },
    { parola: "corre", sillabe: "cor-re", tipo: "verbo" },
    { parola: "veloce", sillabe: "ve-lo-ce" },
    { parola: "sui", sillabe: "sui" },
    { parola: "binari.", sillabe: "bi-na-ri" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "vigile", sillabe: "vi-gi-le" },
    { parola: "ferma", sillabe: "fer-ma", tipo: "verbo" },
    { parola: "le", sillabe: "le" },
    { parola: "macchine", sillabe: "mac-chi-ne" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "i", sillabe: "i" },
    { parola: "bambini", sillabe: "bam-bi-ni" },
    { parola: "attraversano.", sillabe: "at-tra-ver-sa-no", tipo: "verbo" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "signora", sillabe: "si-gno-ra" },
    { parola: "compra", sillabe: "com-pra", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "pane", sillabe: "pa-ne" },
    { parola: "dal", sillabe: "dal" },
    { parola: "fornaio.", sillabe: "for-na-io" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "negozio", sillabe: "ne-go-zio" },
    { parola: "apre", sillabe: "a-pre", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "mattina", sillabe: "mat-ti-na" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "chiude", sillabe: "chiu-de", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "sera.", sillabe: "se-ra" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "bambino", sillabe: "bam-bi-no" },
    { parola: "va", sillabe: "va", tipo: "verbo" },
    { parola: "al", sillabe: "al" },
    { parola: "parco", sillabe: "par-co" },
    { parola: "con", sillabe: "con" },
    { parola: "la", sillabe: "la" },
    { parola: "bicicletta", sillabe: "bi-ci-clet-ta" },
    { parola: "nuova.", sillabe: "nuo-va" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "macchina", sillabe: "mac-chi-na" },
    { parola: "si", sillabe: "si" },
    { parola: "ferma", sillabe: "fer-ma", tipo: "verbo" },
    { parola: "quando", sillabe: "quan-do", tipo: "congiunzione" },
    { parola: "il", sillabe: "il" },
    { parola: "semaforo", sillabe: "se-ma-fo-ro" },
    { parola: "diventa", sillabe: "di-ven-ta", tipo: "verbo" },
    { parola: "rosso.", sillabe: "ros-so" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "postino", sillabe: "po-sti-no" },
    { parola: "porta", sillabe: "por-ta", tipo: "verbo" },
    { parola: "le", sillabe: "le" },
    { parola: "lettere", sillabe: "let-te-re" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "suona", sillabe: "suo-na", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "campanello.", sillabe: "cam-pa-nel-lo" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "nave", sillabe: "na-ve" },
    { parola: "parte", sillabe: "par-te", tipo: "verbo" },
    { parola: "dal", sillabe: "dal" },
    { parola: "porto", sillabe: "por-to" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "va", sillabe: "va", tipo: "verbo" },
    { parola: "lontano.", sillabe: "lon-ta-no" },
  ],
  [
    { parola: "I", sillabe: "I" },
    { parola: "turisti", sillabe: "tu-ri-sti" },
    { parola: "visitano", sillabe: "vi-si-ta-no", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "castello", sillabe: "ca-stel-lo" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "scattano", sillabe: "scat-ta-no", tipo: "verbo" },
    { parola: "le", sillabe: "le" },
    { parola: "foto.", sillabe: "fo-to" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "pescatore", sillabe: "pe-sca-to-re" },
    { parola: "getta", sillabe: "get-ta", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "rete", sillabe: "re-te" },
    { parola: "in", sillabe: "in" },
    { parola: "mare", sillabe: "ma-re" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "aspetta", sillabe: "a-spet-ta", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "pesce.", sillabe: "pe-sce" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "panettiere", sillabe: "pa-net-tie-re" },
    { parola: "sforna", sillabe: "sfor-na", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "pane", sillabe: "pa-ne" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "il", sillabe: "il" },
    { parola: "profumo", sillabe: "pro-fu-mo" },
    { parola: "riempie", sillabe: "riem-pie", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "strada.", sillabe: "stra-da" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "dottore", sillabe: "dot-to-re" },
    { parola: "visita", sillabe: "vi-si-ta", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "paziente", sillabe: "pa-zien-te" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "scrive", sillabe: "scri-ve", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "ricetta.", sillabe: "ri-cet-ta" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "bambino", sillabe: "bam-bi-no" },
    { parola: "ride", sillabe: "ri-de", tipo: "verbo" },
    { parola: "forte", sillabe: "for-te" },
    { parola: "perché", sillabe: "per-ché", tipo: "congiunzione" },
    { parola: "il", sillabe: "il" },
    { parola: "pagliaccio", sillabe: "pa-gliac-cio" },
    { parola: "cade.", sillabe: "ca-de", tipo: "verbo" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "bambina", sillabe: "bam-bi-na" },
    { parola: "piange", sillabe: "pian-ge", tipo: "verbo" },
    { parola: "perché", sillabe: "per-ché", tipo: "congiunzione" },
    { parola: "perde", sillabe: "per-de", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "bambola.", sillabe: "bam-bo-la" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "bimbo", sillabe: "bim-bo" },
    { parola: "stringe", sillabe: "strin-ge", tipo: "verbo" },
    { parola: "forte", sillabe: "for-te" },
    { parola: "il", sillabe: "il" },
    { parola: "pupazzo", sillabe: "pu-paz-zo" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "dorme", sillabe: "dor-me", tipo: "verbo" },
    { parola: "sereno.", sillabe: "se-re-no" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "bambina", sillabe: "bam-bi-na" },
    { parola: "canta", sillabe: "can-ta", tipo: "verbo" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "tutti", sillabe: "tut-ti" },
    { parola: "battono", sillabe: "bat-to-no", tipo: "verbo" },
    { parola: "le", sillabe: "le" },
    { parola: "mani.", sillabe: "ma-ni" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "piccolo", sillabe: "pic-co-lo" },
    { parola: "costruisce", sillabe: "co-strui-sce", tipo: "verbo" },
    { parola: "un", sillabe: "un" },
    { parola: "castello", sillabe: "ca-stel-lo" },
    { parola: "di", sillabe: "di" },
    { parola: "sabbia", sillabe: "sab-bia" },
    { parola: "mentre", sillabe: "men-tre", tipo: "congiunzione" },
    { parola: "il", sillabe: "il" },
    { parola: "mare", sillabe: "ma-re" },
    { parola: "arriva.", sillabe: "ar-ri-va", tipo: "verbo" },
  ],
  [
    { parola: "I", sillabe: "I" },
    { parola: "bambini", sillabe: "bam-bi-ni" },
    { parola: "giocano", sillabe: "gio-ca-no", tipo: "verbo" },
    { parola: "a", sillabe: "a" },
    { parola: "nascondino", sillabe: "na-scon-di-no" },
    { parola: "nel", sillabe: "nel" },
    { parola: "giardino", sillabe: "giar-di-no" },
    { parola: "della", sillabe: "del-la" },
    { parola: "nonna.", sillabe: "non-na" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "bambino", sillabe: "bam-bi-no" },
    { parola: "salta", sillabe: "sal-ta", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "corda", sillabe: "cor-da" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "conta", sillabe: "con-ta", tipo: "verbo" },
    { parola: "fino", sillabe: "fi-no" },
    { parola: "a", sillabe: "a" },
    { parola: "dieci.", sillabe: "die-ci" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "principessa", sillabe: "prin-ci-pes-sa" },
    { parola: "vive", sillabe: "vi-ve", tipo: "verbo" },
    { parola: "nel", sillabe: "nel" },
    { parola: "castello", sillabe: "ca-stel-lo" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "porta", sillabe: "por-ta", tipo: "verbo" },
    { parola: "una", sillabe: "u-na" },
    { parola: "corona", sillabe: "co-ro-na" },
    { parola: "dorata.", sillabe: "do-ra-ta" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "re", sillabe: "re" },
    { parola: "guarda", sillabe: "guar-da", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "regno", sillabe: "re-gno" },
    { parola: "dalla", sillabe: "dal-la" },
    { parola: "torre", sillabe: "tor-re" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "saluta", sillabe: "sa-lu-ta", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "popolo.", sillabe: "po-po-lo" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "pirata", sillabe: "pi-ra-ta" },
    { parola: "cerca", sillabe: "cer-ca", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "tesoro", sillabe: "te-so-ro" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "scava", sillabe: "sca-va", tipo: "verbo" },
    { parola: "nella", sillabe: "nel-la" },
    { parola: "sabbia.", sillabe: "sab-bia" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "drago", sillabe: "dra-go" },
    { parola: "sputa", sillabe: "spu-ta", tipo: "verbo" },
    { parola: "fuoco", sillabe: "fuo-co" },
    { parola: "ma", sillabe: "ma", tipo: "congiunzione" },
    { parola: "il", sillabe: "il" },
    { parola: "cavaliere", sillabe: "ca-va-lie-re" },
    { parola: "resta", sillabe: "re-sta", tipo: "verbo" },
    { parola: "fermo.", sillabe: "fer-mo" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "mago", sillabe: "ma-go" },
    { parola: "agita", sillabe: "a-gi-ta", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "bacchetta", sillabe: "bac-chet-ta" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "appare", sillabe: "ap-pa-re", tipo: "verbo" },
    { parola: "un", sillabe: "un" },
    { parola: "coniglio.", sillabe: "co-ni-glio" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "fata", sillabe: "fa-ta" },
    { parola: "vola", sillabe: "vo-la", tipo: "verbo" },
    { parola: "sopra", sillabe: "so-pra" },
    { parola: "il", sillabe: "il" },
    { parola: "bosco", sillabe: "bo-sco" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "spruzza", sillabe: "spruz-za", tipo: "verbo" },
    { parola: "polvere", sillabe: "pol-ve-re" },
    { parola: "magica.", sillabe: "ma-gi-ca" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "robot", sillabe: "ro-bot" },
    { parola: "cammina", sillabe: "cam-mi-na", tipo: "verbo" },
    { parola: "piano", sillabe: "pia-no" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "porta", sillabe: "por-ta", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "spesa.", sillabe: "spe-sa" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "razzo", sillabe: "raz-zo" },
    { parola: "parte", sillabe: "par-te", tipo: "verbo" },
    { parola: "veloce", sillabe: "ve-lo-ce" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "sale", sillabe: "sa-le", tipo: "verbo" },
    { parola: "verso", sillabe: "ver-so" },
    { parola: "la", sillabe: "la" },
    { parola: "luna.", sillabe: "lu-na" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "bambino", sillabe: "bam-bi-no" },
    { parola: "guarda", sillabe: "guar-da", tipo: "verbo" },
    { parola: "le", sillabe: "le" },
    { parola: "stelle", sillabe: "stel-le" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "sogna", sillabe: "so-gna", tipo: "verbo" },
    { parola: "un", sillabe: "un" },
    { parola: "viaggio", sillabe: "viag-gio" },
    { parola: "nello", sillabe: "nel-lo" },
    { parola: "spazio.", sillabe: "spa-zio" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "pittore", sillabe: "pit-to-re" },
    { parola: "dipinge", sillabe: "di-pin-ge", tipo: "verbo" },
    { parola: "un", sillabe: "un" },
    { parola: "quadro", sillabe: "qua-dro" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "usa", sillabe: "u-sa", tipo: "verbo" },
    { parola: "molti", sillabe: "mol-ti" },
    { parola: "colori.", sillabe: "co-lo-ri" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "musicista", sillabe: "mu-si-ci-sta" },
    { parola: "suona", sillabe: "suo-na", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "pianoforte", sillabe: "pia-no-for-te" },
    { parola: "mentre", sillabe: "men-tre", tipo: "congiunzione" },
    { parola: "gli", sillabe: "gli" },
    { parola: "ospiti", sillabe: "o-spi-ti" },
    { parola: "ascoltano.", sillabe: "a-scol-ta-no", tipo: "verbo" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "cantante", sillabe: "can-tan-te" },
    { parola: "canta", sillabe: "can-ta", tipo: "verbo" },
    { parola: "una", sillabe: "u-na" },
    { parola: "canzone", sillabe: "can-zo-ne" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "la", sillabe: "la" },
    { parola: "folla", sillabe: "fol-la" },
    { parola: "balla.", sillabe: "bal-la", tipo: "verbo" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "ballerina", sillabe: "bal-le-ri-na" },
    { parola: "danza", sillabe: "dan-za", tipo: "verbo" },
    { parola: "sul", sillabe: "sul" },
    { parola: "palco", sillabe: "pal-co" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "gira", sillabe: "gi-ra", tipo: "verbo" },
    { parola: "piano.", sillabe: "pia-no" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "campione", sillabe: "cam-pio-ne" },
    { parola: "corre", sillabe: "cor-re", tipo: "verbo" },
    { parola: "veloce", sillabe: "ve-lo-ce" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "vince", sillabe: "vin-ce", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "gara.", sillabe: "ga-ra" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "portiere", sillabe: "por-tie-re" },
    { parola: "para", sillabe: "pa-ra", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "pallone", sillabe: "pal-lo-ne" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "la", sillabe: "la" },
    { parola: "squadra", sillabe: "squa-dra" },
    { parola: "esulta.", sillabe: "e-sul-ta", tipo: "verbo" },
  ],
  [
    { parola: "I", sillabe: "I" },
    { parola: "giocatori", sillabe: "gio-ca-to-ri" },
    { parola: "entrano", sillabe: "en-tra-no", tipo: "verbo" },
    { parola: "in", sillabe: "in" },
    { parola: "campo", sillabe: "cam-po" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "il", sillabe: "il" },
    { parola: "pubblico", sillabe: "pub-bli-co" },
    { parola: "applaude.", sillabe: "ap-plau-de", tipo: "verbo" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "nuotatrice", sillabe: "nuo-ta-tri-ce" },
    { parola: "salta", sillabe: "sal-ta", tipo: "verbo" },
    { parola: "in", sillabe: "in" },
    { parola: "acqua", sillabe: "ac-qua" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "nuota", sillabe: "nuo-ta", tipo: "verbo" },
    { parola: "veloce.", sillabe: "ve-lo-ce" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "ciclista", sillabe: "ci-cli-sta" },
    { parola: "pedala", sillabe: "pe-da-la", tipo: "verbo" },
    { parola: "forte", sillabe: "for-te" },
    { parola: "quando", sillabe: "quan-do", tipo: "congiunzione" },
    { parola: "inizia", sillabe: "i-ni-zia", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "salita.", sillabe: "sa-li-ta" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "bambino", sillabe: "bam-bi-no" },
    { parola: "impara", sillabe: "im-pa-ra", tipo: "verbo" },
    { parola: "a", sillabe: "a" },
    { parola: "nuotare", sillabe: "nuo-ta-re" },
    { parola: "mentre", sillabe: "men-tre", tipo: "congiunzione" },
    { parola: "il", sillabe: "il" },
    { parola: "papà", sillabe: "pa-pà" },
    { parola: "lo", sillabe: "lo" },
    { parola: "aiuta.", sillabe: "a-iu-ta", tipo: "verbo" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "cane", sillabe: "ca-ne" },
    { parola: "rincorre", sillabe: "rin-cor-re", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "palla", sillabe: "pal-la" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "la", sillabe: "la" },
    { parola: "porta", sillabe: "por-ta", tipo: "verbo" },
    { parola: "al", sillabe: "al" },
    { parola: "padrone.", sillabe: "pa-dro-ne" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "gatta", sillabe: "gat-ta" },
    { parola: "lecca", sillabe: "lec-ca", tipo: "verbo" },
    { parola: "i", sillabe: "i" },
    { parola: "gattini", sillabe: "gat-ti-ni" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "li", sillabe: "li" },
    { parola: "porta", sillabe: "por-ta", tipo: "verbo" },
    { parola: "nel", sillabe: "nel" },
    { parola: "cesto.", sillabe: "ce-sto" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "pappagallo", sillabe: "pap-pa-gal-lo" },
    { parola: "ripete", sillabe: "ri-pe-te", tipo: "verbo" },
    { parola: "le", sillabe: "le" },
    { parola: "parole", sillabe: "pa-ro-le" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "tutti", sillabe: "tut-ti" },
    { parola: "ridono.", sillabe: "ri-do-no", tipo: "verbo" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "canarino", sillabe: "ca-na-ri-no" },
    { parola: "canta", sillabe: "can-ta", tipo: "verbo" },
    { parola: "nella", sillabe: "nel-la" },
    { parola: "gabbia", sillabe: "gab-bia" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "saltella", sillabe: "sal-tel-la", tipo: "verbo" },
    { parola: "sul", sillabe: "sul" },
    { parola: "trespolo.", sillabe: "tre-spo-lo" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "pesciolino", sillabe: "pe-scio-li-no" },
    { parola: "nuota", sillabe: "nuo-ta", tipo: "verbo" },
    { parola: "in", sillabe: "in" },
    { parola: "cerchio", sillabe: "cer-chio" },
    { parola: "nella", sillabe: "nel-la" },
    { parola: "boccia.", sillabe: "boc-cia" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "lumaca", sillabe: "lu-ma-ca" },
    { parola: "lascia", sillabe: "la-scia", tipo: "verbo" },
    { parola: "una", sillabe: "u-na" },
    { parola: "scia", sillabe: "scia" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "porta", sillabe: "por-ta", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "casa", sillabe: "ca-sa" },
    { parola: "sulla", sillabe: "sul-la" },
    { parola: "schiena.", sillabe: "schie-na" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "riccio", sillabe: "ric-cio" },
    { parola: "si", sillabe: "si" },
    { parola: "chiude", sillabe: "chiu-de", tipo: "verbo" },
    { parola: "a", sillabe: "a" },
    { parola: "palla", sillabe: "pal-la" },
    { parola: "quando", sillabe: "quan-do", tipo: "congiunzione" },
    { parola: "vede", sillabe: "ve-de", tipo: "verbo" },
    { parola: "il", sillabe: "il" },
    { parola: "cane.", sillabe: "ca-ne" },
  ],
  [
    { parola: "Lo", sillabe: "Lo" },
    { parola: "scoiattolo", sillabe: "sco-iat-to-lo" },
    { parola: "raccoglie", sillabe: "rac-co-glie", tipo: "verbo" },
    { parola: "le", sillabe: "le" },
    { parola: "noci", sillabe: "no-ci" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "corre", sillabe: "cor-re", tipo: "verbo" },
    { parola: "sul", sillabe: "sul" },
    { parola: "tronco.", sillabe: "tron-co" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "civetta", sillabe: "ci-vet-ta" },
    { parola: "vola", sillabe: "vo-la", tipo: "verbo" },
    { parola: "di", sillabe: "di" },
    { parola: "notte", sillabe: "not-te" },
    { parola: "mentre", sillabe: "men-tre", tipo: "congiunzione" },
    { parola: "il", sillabe: "il" },
    { parola: "bosco", sillabe: "bo-sco" },
    { parola: "dorme.", sillabe: "dor-me", tipo: "verbo" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "pinguino", sillabe: "pin-gui-no" },
    { parola: "scivola", sillabe: "sci-vo-la", tipo: "verbo" },
    { parola: "sul", sillabe: "sul" },
    { parola: "ghiaccio", sillabe: "ghiac-cio" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "si", sillabe: "si" },
    { parola: "tuffa", sillabe: "tuf-fa", tipo: "verbo" },
    { parola: "nel", sillabe: "nel" },
    { parola: "mare.", sillabe: "ma-re" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "balena", sillabe: "ba-le-na" },
    { parola: "spruzza", sillabe: "spruz-za", tipo: "verbo" },
    { parola: "acqua", sillabe: "ac-qua" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "nuota", sillabe: "nuo-ta", tipo: "verbo" },
    { parola: "lontano.", sillabe: "lon-ta-no" },
  ],
  [
    { parola: "Il", sillabe: "Il" },
    { parola: "delfino", sillabe: "del-fi-no" },
    { parola: "salta", sillabe: "sal-ta", tipo: "verbo" },
    { parola: "fuori", sillabe: "fuo-ri" },
    { parola: "dal", sillabe: "dal" },
    { parola: "mare", sillabe: "ma-re" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "i", sillabe: "i" },
    { parola: "bambini", sillabe: "bam-bi-ni" },
    { parola: "battono", sillabe: "bat-to-no", tipo: "verbo" },
    { parola: "le", sillabe: "le" },
    { parola: "mani.", sillabe: "ma-ni" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "stella", sillabe: "stel-la" },
    { parola: "marina", sillabe: "ma-ri-na" },
    { parola: "vive", sillabe: "vi-ve", tipo: "verbo" },
    { parola: "sugli", sillabe: "su-gli" },
    { parola: "scogli", sillabe: "sco-gli" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "aspetta", sillabe: "a-spet-ta", tipo: "verbo" },
    { parola: "la", sillabe: "la" },
    { parola: "marea.", sillabe: "ma-re-a" },
  ],
  [
    { parola: "La", sillabe: "La" },
    { parola: "mamma", sillabe: "mam-ma" },
    { parola: "legge", sillabe: "leg-ge", tipo: "verbo" },
    { parola: "una", sillabe: "u-na" },
    { parola: "favola", sillabe: "fa-vo-la" },
    { parola: "e", sillabe: "e", tipo: "congiunzione" },
    { parola: "il", sillabe: "il" },
    { parola: "bimbo", sillabe: "bim-bo" },
    { parola: "chiude", sillabe: "chiu-de", tipo: "verbo" },
    { parola: "gli", sillabe: "gli" },
    { parola: "occhi.", sillabe: "oc-chi" },
  ],
];
